import { Brand, Product } from './types';

export const BRANDS: Brand[] = [
  { id: 'cali-ul8000', name: 'Cali UL 8000', tagline: 'Silky smooth hits with silicone tip', puffRange: '8000 Puffs', description: 'Known for its comfortable silicone mouthpiece and consistent flavor delivery.', image: 'https://placehold.co/600x600/1a1a1a/D4AF37?text=Cali+UL+8000', category: 'disposable-vapes' },
  { id: 'cali-20000', name: 'Cali 20000', tagline: 'Massive capacity for extended use', puffRange: '20000 Puffs', description: 'A powerhouse device designed for longevity without sacrificing flavor intensity.', image: 'https://placehold.co/600x600/1a1a1a/D4AF37?text=Cali+20000', category: 'disposable-vapes' },
  { id: 'yme-nic', name: 'YME 5%', tagline: 'Pure tobacco leaf extraction', puffRange: '5000 Puffs', description: 'Focused on authentic tobacco and straightforward blends.', image: '/images/yme-nic/brand-card.png', category: 'disposable-vapes' },
  { id: 'yme-nonic', name: 'YME 0%', tagline: 'Zero nicotine, full flavor', puffRange: '5000 Puffs', description: 'The perfect choice for those who want the sensation without the nicotine.', image: '/images/yme-nonic/brand-card.png', category: 'disposable-vapes' },
  { id: 'lava-plus', name: 'Lava Plus', tagline: 'Bold flavors in a compact design', puffRange: '2600 Puffs', description: 'A reliable choice with a vast array of intense fruit and dessert profiles.', image: 'https://placehold.co/600x600/1a1a1a/D4AF37?text=Lava+Plus', category: 'disposable-vapes' },
  { id: 'flair-ultra', name: 'Flair Ultra', tagline: 'Compact premium design', puffRange: '2500 Puffs', description: 'Sleek, portable, and packed with intense flavor profiles.', image: 'https://placehold.co/600x600/1a1a1a/D4AF37?text=Flair+Ultra', category: 'disposable-vapes' },
  { id: 'airbar-diamond', name: 'Airbar Diamond', tagline: 'Jewel-inspired elegance', puffRange: '500 Puffs', description: 'A classic, stylish choice with a hard shell design and smooth draw.', image: 'https://placehold.co/600x600/1a1a1a/D4AF37?text=Airbar+Diamond', category: 'disposable-vapes' },
  { id: 'geekbar-pulse', name: 'Geek Bar Pulse', tagline: 'World’s first full screen disposable', puffRange: '15000 Puffs', description: 'Features Pulse Mode for enhanced airflow and flavor, plus a large display.', image: 'https://placehold.co/600x600/1a1a1a/D4AF37?text=Geek+Bar+Pulse', category: 'disposable-vapes' },
  { id: 'geekbar-pulsex', name: 'Geekbar Pulse X', tagline: 'Next gen pulse technology', puffRange: '25000 Puffs', description: 'Curved screen display and starry sky UI with faster charging.', image: 'https://placehold.co/600x600/1a1a1a/D4AF37?text=Geek+Bar+Pulse+X', category: 'disposable-vapes' },
  { id: 'tyson-30k', name: 'Tyson', tagline: 'The Undisputed Champion of Vapes', puffRange: '30000 Puffs', description: 'A heavyweight 30,000 puff device featuring dual power modes and a 3D curved display screen.', image: '/images/tyson-30k/brand-card.png', category: 'disposable-vapes' },
  { id: 'olit-hookalit', name: 'Olit Hookalit', tagline: 'Mystical E-Hookah Experience', puffRange: '40000 Puffs', description: 'A massive 40,000 puff e-hookah device with Tarot-style artwork, dual power modes, and dense cloud production.', image: '/images/olit-hookalit/brand-card.png', category: 'disposable-vapes' },
];

const RAW_PRODUCT_DATA = [
  // Cali 8k
  { brandId: 'cali-ul8000', name: 'Blue Raspberry Lemonade', code: '(C8K)', image: '/images/cali-ul8000/blue-raspberry-lemonade.jpg' },
  { brandId: 'cali-ul8000', name: 'Frozen Apple Watermelon', code: '(C8K)', image: '/images/cali-ul8000/frozen-apple-watermelon.jpg' },
  { brandId: 'cali-ul8000', name: 'Frozen Blackberry', code: '(C8K)', image: '/images/cali-ul8000/frozen-blackberry.jpg' },
  { brandId: 'cali-ul8000', name: 'Frozen Blue Raspberry', code: '(C8K)', image: '/images/cali-ul8000/frozen-blue-raspberry.jpg' },
  { brandId: 'cali-ul8000', name: 'Frozen Grape', code: '(C8K)', image: '/images/cali-ul8000/frozen-grape.jpg' },
  { brandId: 'cali-ul8000', name: 'Frozen Lush', code: '(C8K)', image: '/images/cali-ul8000/frozen-lush.jpg' },
  { brandId: 'cali-ul8000', name: 'Frozen Peach', code: '(C8K)', image: '/images/cali-ul8000/frozen-peach.jpg' },
  { brandId: 'cali-ul8000', name: 'Frozen Strawberry Raspberry', code: '(C8K)', image: '/images/cali-ul8000/frozen-strawberry-raspberry.jpg' },
  { brandId: 'cali-ul8000', name: 'Frozen Banana', code: '(C8K)', image: '/images/cali-ul8000/frozen-banana.jpg' },
  { brandId: 'cali-ul8000', name: 'Frozen Kiwi Lemonade', code: '(C8K)' },
  { brandId: 'cali-ul8000', name: 'Frozen Watermelon', code: '(C8K)' },
  { brandId: 'cali-ul8000', name: 'Mighty Mint', code: '(C8K)', image: '/images/cali-ul8000/mighty-mint.jpg' },
  { brandId: 'cali-ul8000', name: 'Mexican Mint', code: '(C8K)' },
  { brandId: 'cali-ul8000', name: 'LA Mint', code: '(C8K)' },
  { brandId: 'cali-ul8000', name: 'Peach Watermelon', code: '(C8K)', image: '/images/cali-ul8000/peach-watermelon.jpg' },
  { brandId: 'cali-ul8000', name: 'Peach Mango Watermelon', code: '(C8K)', image: '/images/cali-ul8000/peach-mango-watermelon.jpg' },
  { brandId: 'cali-ul8000', name: 'Pineapple Splash', code: '(C8K)', image: '/images/cali-ul8000/pineapple-splash.jpg' },
  { brandId: 'cali-ul8000', name: 'Pineapple Strawberry Banana', code: '(C8K)', image: '/images/cali-ul8000/pineapple-strawberry-banana.jpg' },
  { brandId: 'cali-ul8000', name: 'Strawberry Banana', code: '(C8K)', image: '/images/cali-ul8000/strawberry-banana.jpg' },
  { brandId: 'cali-ul8000', name: 'Strawberry Kiwi', code: '(C8K)', image: '/images/cali-ul8000/strawberry-kiwi.jpg' },
  { brandId: 'cali-ul8000', name: 'Triple Berry', code: '(C8K)' },
  { brandId: 'cali-ul8000', name: 'Watermelon Splash', code: '(C8K)', image: '/images/cali-ul8000/watermelon-splash.jpg' },
  { brandId: 'cali-ul8000', name: 'Kiwi Dragon Berry', code: '(C8K)', image: '/images/cali-ul8000/kiwi-dragon-berry.jpg' },
  { brandId: 'cali-ul8000', name: 'Spearmint', code: '(C8K)' },
  { brandId: 'cali-ul8000', name: 'Polar Ice', code: '(C8K)', image: '/images/cali-ul8000/polar-ice.jpg' },
  { brandId: 'cali-ul8000', name: 'Cherry Lemonade', code: '(C8K)' },
  { brandId: 'cali-ul8000', name: 'Grape', code: '(C8K)' },
  { brandId: 'cali-ul8000', name: 'Strawberry Watermelon', code: '(C8K)' },
  { brandId: 'cali-ul8000', name: 'Fruity Loop', code: '(C8K)' },
  { brandId: 'cali-ul8000', name: 'Cosmic Blast', code: '(C8K)' },
  { brandId: 'cali-ul8000', name: 'Guava Frenzy', code: '(C8K)' },

  // Cali 20k
  { brandId: 'cali-20000', name: 'Blue Raspberry Lemonade', code: '(C20K)' },
  { brandId: 'cali-20000', name: 'Cherry Lemonade', code: '(C20K)' },
  { brandId: 'cali-20000', name: 'Frozen Apple Watermelon', code: '(C20K)' },
  { brandId: 'cali-20000', name: 'Frozen Banana', code: '(C20K)' },
  { brandId: 'cali-20000', name: 'Frozen Blackberry', code: '(C20K)' },
  { brandId: 'cali-20000', name: 'Frozen Blue Raspberry', code: '(C20K)' },
  { brandId: 'cali-20000', name: 'Frozen Grape', code: '(C20K)' },
  { brandId: 'cali-20000', name: 'Frozen Kiwi Lemonade', code: '(C20K)' },
  { brandId: 'cali-20000', name: 'Frozen Lush', code: '(C20K)' },
  { brandId: 'cali-20000', name: 'Frozen Peach', code: '(C20K)' },
  { brandId: 'cali-20000', name: 'Frozen Strawberry Raspberry', code: '(C20K)' },
  { brandId: 'cali-20000', name: 'Frozen Watermelon', code: '(C20K)' },
  { brandId: 'cali-20000', name: 'Mighty Mint', code: '(C20K)' },
  { brandId: 'cali-20000', name: 'LA Mint', code: '(C20K)' },
  { brandId: 'cali-20000', name: 'Peach Mango Watermelon', code: '(C20K)' },
  { brandId: 'cali-20000', name: 'Peach Watermelon', code: '(C20K)' },
  { brandId: 'cali-20000', name: 'Pineapple Splash', code: '(C20K)' },
  { brandId: 'cali-20000', name: 'Pineapple Strawberry Banana', code: '(C20K)' },
  { brandId: 'cali-20000', name: 'Triple Berry', code: '(C20K)' },
  { brandId: 'cali-20000', name: 'Watermelon Splash', code: '(C20K)' },
  { brandId: 'cali-20000', name: 'Coconut Banana', code: '(C20K)' },
  { brandId: 'cali-20000', name: 'Strawberry Kiwi', code: '(C20K)' },
  { brandId: 'cali-20000', name: 'Strawberry Banana', code: '(C20K)' },
  { brandId: 'cali-20000', name: 'Kiwi Dragon Berry', code: '(C20K)' },
  { brandId: 'cali-20000', name: 'Spearmint', code: '(C20K)' },
  { brandId: 'cali-20000', name: 'Polar Ice', code: '(C20K)' },
  { brandId: 'cali-20000', name: 'Russian Cream', code: '(C20K)' },
  { brandId: 'cali-20000', name: 'Sour Grape', code: '(C20K)' },
  { brandId: 'cali-20000', name: 'Clear', code: '(C20K)' },
  { brandId: 'cali-20000', name: 'Tobacco', code: '(C20K)' },
  { brandId: 'cali-20000', name: 'Frozen Sour Apple', code: '(C20K)' },
  { brandId: 'cali-20000', name: 'Frozen Sour Peach', code: '(C20K)' },
  { brandId: 'cali-20000', name: 'Sour Blueberry', code: '(C20K)' },
  { brandId: 'cali-20000', name: 'Sour Lush', code: '(C20K)' },
  { brandId: 'cali-20000', name: 'Sour Watermelon', code: '(C20K)' },
  { brandId: 'cali-20000', name: 'Emerald Green Mint', code: '(C20K)' },
  { brandId: 'cali-20000', name: 'Menthol', code: '(C20K)' },
  { brandId: 'cali-20000', name: 'Mint', code: '(C20K)' },
  { brandId: 'cali-20000', name: 'Peppermint', code: '(C20K)' },
  { brandId: 'cali-20000', name: 'Wintergreen Mint', code: '(C20K)' },
  { brandId: 'cali-20000', name: 'Meta Moon', code: '(C20K)' },
  { brandId: 'cali-20000', name: 'Fucking Fab', code: '(C20K)' },
  { brandId: 'cali-20000', name: 'Blue Mint', code: '(C20K)' },
  { brandId: 'cali-20000', name: 'Baja Blast', code: '(C20K)' },
  { brandId: 'cali-20000', name: 'Sour Fckuing Fab', code: '(C20K)' },

  // YME 5%
  { brandId: 'yme-nic', name: 'Apple Ice', code: '(YME5%)' },
  { brandId: 'yme-nic', name: 'Banana', code: '(YME5%)' },
  { brandId: 'yme-nic', name: 'Banana Ice', code: '(YME5%)' },
  { brandId: 'yme-nic', name: 'Berry Mist', code: '(YME5%)' },
  { brandId: 'yme-nic', name: 'Black Ice', code: '(YME5%)' },
  { brandId: 'yme-nic', name: 'Blue Raz', code: '(YME5%)' },
  { brandId: 'yme-nic', name: 'Blue Raz Cherry', code: '(YME5%)' },
  { brandId: 'yme-nic', name: 'Blueberry Ice', code: '(YME5%)' },
  { brandId: 'yme-nic', name: 'Clear', code: '(YME5%)' },
  { brandId: 'yme-nic', name: 'Clear Ice', code: '(YME5%)' },
  { brandId: 'yme-nic', name: 'Cola Ice', code: '(YME5%)' },
  { brandId: 'yme-nic', name: 'Cool Mint', code: '(YME5%)' },
  { brandId: 'yme-nic', name: 'Cranberry Grape', code: '(YME5%)' },
  { brandId: 'yme-nic', name: 'Energy Power', code: '(YME5%)' },
  { brandId: 'yme-nic', name: 'Fruit Rainbow', code: '(YME5%)' },
  { brandId: 'yme-nic', name: 'Grape Ice', code: '(YME5%)' },
  { brandId: 'yme-nic', name: 'Havana Tobacco', code: '(YME5%)' },
  { brandId: 'yme-nic', name: 'Jolly Rancher', code: '(YME5%)' },
  { brandId: 'yme-nic', name: 'Juicy Peach Ice', code: '(YME5%)' },
  { brandId: 'yme-nic', name: 'Kiwi Passion Fruit Guava', code: '(YME5%)' },
  { brandId: 'yme-nic', name: 'Lush Ice', code: '(YME5%)' },
  { brandId: 'yme-nic', name: 'Mango Ice', code: '(YME5%)' },
  { brandId: 'yme-nic', name: 'Mint Ice', code: '(YME5%)' },
  { brandId: 'yme-nic', name: 'Nerdz Ice', code: '(YME5%)' },
  { brandId: 'yme-nic', name: 'Orange Peach Pineapple Ice', code: '(YME5%)' },
  { brandId: 'yme-nic', name: 'Orange Soda', code: '(YME5%)' },
  { brandId: 'yme-nic', name: 'Passion Fruit Ice', code: '(YME5%)' },
  { brandId: 'yme-nic', name: 'Peach Ice', code: '(YME5%)' },
  { brandId: 'yme-nic', name: 'Peach Mango', code: '(YME5%)' },
  { brandId: 'yme-nic', name: 'Peach Mango Watermelon', code: '(YME5%)' },
  { brandId: 'yme-nic', name: 'Pineapple Mango', code: '(YME5%)' },
  { brandId: 'yme-nic', name: 'Raspberry Grape Black Currant', code: '(YME5%)' },
  { brandId: 'yme-nic', name: 'Raspberry Lemonade', code: '(YME5%)' },
  { brandId: 'yme-nic', name: 'Skittles', code: '(YME5%)' },
  { brandId: 'yme-nic', name: 'Sour Apple', code: '(YME5%)' },
  { brandId: 'yme-nic', name: 'Strawberry Banana', code: '(YME5%)' },
  { brandId: 'yme-nic', name: 'Strawberry Guava', code: '(YME5%)' },
  { brandId: 'yme-nic', name: 'Strawberry Ice', code: '(YME5%)' },
  { brandId: 'yme-nic', name: 'Strawberry Ice Cream', code: '(YME5%)' },
  { brandId: 'yme-nic', name: 'Strawberry Lemon Mint', code: '(YME5%)' },
  { brandId: 'yme-nic', name: 'Strawberry Mango', code: '(YME5%)' },
  { brandId: 'yme-nic', name: 'Strawberry Raspberry', code: '(YME5%)' },
  { brandId: 'yme-nic', name: 'Watermelon Kiwi', code: '(YME5%)' },
  { brandId: 'yme-nic', name: 'Watermelon Strawberry', code: '(YME5%)' },
  { brandId: 'yme-nic', name: 'Watermelon Strawberry Bubblegum', code: '(YME5%)' },
  { brandId: 'yme-nic', name: 'Watermelon With Mint', code: '(YME5%)' },

  // YME 0%
  { brandId: 'yme-nonic', name: 'Clear Ice', code: '(YME0%)' },
  { brandId: 'yme-nonic', name: 'Black Ice', code: '(YME0%)' },
  { brandId: 'yme-nonic', name: 'Skittles', code: '(YME0%)' },
  { brandId: 'yme-nonic', name: 'Jolly Ranch (Jolly Rancher)', code: '(YME0%)' },
  { brandId: 'yme-nonic', name: 'Spearmint (Spare mint)', code: '(YME0%)' },
  { brandId: 'yme-nonic', name: 'Watermelon With Mint', code: '(YME0%)' },
  { brandId: 'yme-nonic', name: 'Cool Mint', code: '(YME0%)' },
  { brandId: 'yme-nonic', name: 'Lush Ice', code: '(YME0%)' },
  { brandId: 'yme-nonic', name: 'Blueberry Ice', code: '(YME0%)' },
  { brandId: 'yme-nonic', name: 'Grape Ice', code: '(YME0%)' },
  { brandId: 'yme-nonic', name: 'Watermelon Strawberry', code: '(YME0%)' },
  { brandId: 'yme-nonic', name: 'Peach Mango', code: '(YME0%)' },
  { brandId: 'yme-nonic', name: 'Mango Ice', code: '(YME0%)' },
  { brandId: 'yme-nonic', name: 'Blue Raz (Blue Razz)', code: '(YME0%)' },
  { brandId: 'yme-nonic', name: 'Peach Mango Watermelon', code: '(YME0%)' },
  { brandId: 'yme-nonic', name: 'Peach Mango Strawberry', code: '(YME0%)' },
  { brandId: 'yme-nonic', name: 'Strawberry Ice', code: '(YME0%)' },
  { brandId: 'yme-nonic', name: 'Strawberry Banana', code: '(YME0%)' },
  { brandId: 'yme-nonic', name: 'Apple Ice', code: '(YME0%)' },
  { brandId: 'yme-nonic', name: 'Peach Ice', code: '(YME0%)' },
  { brandId: 'yme-nonic', name: 'Watermelon Blue Raz / Watermelon Blueberry Raz', code: '(YME0%)' },
  { brandId: 'yme-nonic', name: 'Colombian Tobacco', code: '(YME0%)' },
  { brandId: 'yme-nonic', name: 'Juicy Peach Ice', code: '(YME0%)' },

  // Lava Plus
  { brandId: 'lava-plus', name: 'Apple Peach Ice', code: '(LP)' },
  { brandId: 'lava-plus', name: 'Banana', code: '(LP)' },
  { brandId: 'lava-plus', name: 'Banana Milkshake', code: '(LP)' },
  { brandId: 'lava-plus', name: 'Berry Mist', code: '(LP)' },
  { brandId: 'lava-plus', name: 'Black Ice', code: '(LP)' },
  { brandId: 'lava-plus', name: 'Bloom', code: '(LP)' },
  { brandId: 'lava-plus', name: 'Block Ice', code: '(LP)' },
  { brandId: 'lava-plus', name: 'Blueberry Raspberry Lemon', code: '(LP)' },
  { brandId: 'lava-plus', name: 'Cherry Banana', code: '(LP)' },
  { brandId: 'lava-plus', name: 'Clear', code: '(LP)' },
  { brandId: 'lava-plus', name: 'Clear Ice', code: '(LP)' },
  { brandId: 'lava-plus', name: 'Coffee Latte', code: '(LP)' },
  { brandId: 'lava-plus', name: 'Cool Mint', code: '(LP)' },
  { brandId: 'lava-plus', name: 'Cuban Tobacco', code: '(LP)' },
  { brandId: 'lava-plus', name: 'Dragon Flume / Dragon Fume', code: '(LP)' },
  { brandId: 'lava-plus', name: 'Fruit Blast (Skittles)', code: '(LP)' },
  { brandId: 'lava-plus', name: 'Fruit Ice', code: '(LP)' },
  { brandId: 'lava-plus', name: 'Grape Soda', code: '(LP)' },
  { brandId: 'lava-plus', name: 'Grapefruit Ice', code: '(LP)' },
  { brandId: 'lava-plus', name: 'Guava Ice', code: '(LP)' },
  { brandId: 'lava-plus', name: 'Havana Tobacco', code: '(LP)' },
  { brandId: 'lava-plus', name: 'Honey Apple', code: '(LP)' },
  { brandId: 'lava-plus', name: 'Icy Mint', code: '(LP)' },
  { brandId: 'lava-plus', name: 'Jolly Ice / Jolly Rancher Ice', code: '(LP)' },
  { brandId: 'lava-plus', name: 'Kiwi Strawberry', code: '(LP)' },
  { brandId: 'lava-plus', name: 'Lemon Mint / Lemon with Mint', code: '(LP)' },
  { brandId: 'lava-plus', name: 'Mango Ice', code: '(LP)' },
  { brandId: 'lava-plus', name: 'Melon Ice', code: '(LP)' },
  { brandId: 'lava-plus', name: 'Mojito', code: '(LP)' },
  { brandId: 'lava-plus', name: 'Orange Ice', code: '(LP)' },
  { brandId: 'lava-plus', name: 'Passion Fruit Orange Guava', code: '(LP)' },
  { brandId: 'lava-plus', name: 'Peach Ice', code: '(LP)' },
  { brandId: 'lava-plus', name: 'Peach Mango Sour', code: '(LP)' },
  { brandId: 'lava-plus', name: 'Peach Mango Watermelon', code: '(LP)' },
  { brandId: 'lava-plus', name: 'Pineapple Coconut Rum', code: '(LP)' },
  { brandId: 'lava-plus', name: 'Pineapple Mango Sour', code: '(LP)' },
  { brandId: 'lava-plus', name: 'Skittlrs / Skittles (Fruit Blast)', code: '(LP)' },
  { brandId: 'lava-plus', name: 'Solo Mint', code: '(LP)' },
  { brandId: 'lava-plus', name: 'Sour Apple Ice', code: '(LP)' },
  { brandId: 'lava-plus', name: 'Sour Patch', code: '(LP)' },
  { brandId: 'lava-plus', name: 'Sour Watermelon Candy', code: '(LP)' },
  { brandId: 'lava-plus', name: 'Splash Ice', code: '(LP)' },
  { brandId: 'lava-plus', name: 'Spearmint', code: '(LP)' },
  { brandId: 'lava-plus', name: 'Strawberry Banana', code: '(LP)' },
  { brandId: 'lava-plus', name: 'Strawberry Ice', code: '(LP)' },
  { brandId: 'lava-plus', name: 'Strawberry Lemon Mint', code: '(LP)' },
  { brandId: 'lava-plus', name: 'Strawberry Milkshake / Strawberry Quake', code: '(LP)' },
  { brandId: 'lava-plus', name: 'Strawberry Watermelon Bubblegum', code: '(LP)' },
  { brandId: 'lava-plus', name: 'Vanilla Custard', code: '(LP)' },
  { brandId: 'lava-plus', name: 'Watermelon Mint / Watermelon with Mint', code: '(LP)' },

  // Flair Ultra
  { brandId: 'flair-ultra', name: 'Smooth Tobacco', code: '(FU)' },
  { brandId: 'flair-ultra', name: 'Menthol', code: '(FU)' },
  { brandId: 'flair-ultra', name: 'Cool Mint', code: '(FU)' },
  { brandId: 'flair-ultra', name: 'Clear', code: '(FU)' },
  { brandId: 'flair-ultra', name: 'Banana Ice', code: '(FU)' },
  { brandId: 'flair-ultra', name: 'Black Ice', code: '(FU)' },
  { brandId: 'flair-ultra', name: 'Blueberry Mint', code: '(FU)' },
  { brandId: 'flair-ultra', name: 'Blue Razz Ice', code: '(FU)' },
  { brandId: 'flair-ultra', name: 'Cherry Cola', code: '(FU)' },
  { brandId: 'flair-ultra', name: 'Cherry Lemon', code: '(FU)' },
  { brandId: 'flair-ultra', name: 'Grape Ice', code: '(FU)' },
  { brandId: 'flair-ultra', name: 'Peach Ice', code: '(FU)' },
  { brandId: 'flair-ultra', name: 'Peach Mango', code: '(FU)' },
  { brandId: 'flair-ultra', name: 'Raspberry Peach Lime', code: '(FU)' },
  { brandId: 'flair-ultra', name: 'Red Apple', code: '(FU)' },
  { brandId: 'flair-ultra', name: 'Splash Ice', code: '(FU)' },
  { brandId: 'flair-ultra', name: 'Strawberry Guava Ice', code: '(FU)' },
  { brandId: 'flair-ultra', name: 'Strawberry Ice', code: '(FU)' },
  { brandId: 'flair-ultra', name: 'Strawberry Kiwi', code: '(FU)' },
  { brandId: 'flair-ultra', name: 'Watermelon Mint', code: '(FU)' },

  // Airbar Diamond
  { brandId: 'airbar-diamond', name: 'Blueberry Ice', code: '(AD)' },
  { brandId: 'airbar-diamond', name: 'Watermelon Ice', code: '(AD)' },
  { brandId: 'airbar-diamond', name: 'Mango', code: '(AD)' },
  { brandId: 'airbar-diamond', name: 'Mango Strawberry', code: '(AD)' },
  { brandId: 'airbar-diamond', name: 'Strawberry Watermelon', code: '(AD)' },
  { brandId: 'airbar-diamond', name: 'Watermelon Candy', code: '(AD)' },
  { brandId: 'airbar-diamond', name: 'Banana Ice', code: '(AD)' },
  { brandId: 'airbar-diamond', name: 'Banana Pineapple', code: '(AD)' },
  { brandId: 'airbar-diamond', name: 'Pineapple Ice', code: '(AD)' },
  { brandId: 'airbar-diamond', name: 'Peach', code: '(AD)' },
  { brandId: 'airbar-diamond', name: 'Cool Mint', code: '(AD)' },
  { brandId: 'airbar-diamond', name: 'Grape Ice', code: '(AD)' },
  { brandId: 'airbar-diamond', name: 'Cherry Cola', code: '(AD)' },
  { brandId: 'airbar-diamond', name: 'Kiwi Berry Ice', code: '(AD)' },
  { brandId: 'airbar-diamond', name: 'Peach Blueberry Candy', code: '(AD)' },
  { brandId: 'airbar-diamond', name: 'Red Mojito', code: '(AD)' },
  { brandId: 'airbar-diamond', name: 'Love Story', code: '(AD)' },
  { brandId: 'airbar-diamond', name: 'Sour Apple Ice', code: '(AD)' },
  { brandId: 'airbar-diamond', name: 'Juicy Peach Ice', code: '(AD)' },
  { brandId: 'airbar-diamond', name: 'Clear', code: '(AD)' },

  // Geek Bar Pulse
  // Geek Bar Pulse
  { brandId: 'geekbar-pulse', name: 'Watermelon Ice', code: '(GB P)', description: 'sweet, juicy watermelon with a medium–strong menthol/ice', battery: '650 mAh', nicotine: '5%', isRechargeable: true },
  { brandId: 'geekbar-pulse', name: 'Blue Razz Ice', code: '(GB P)', description: 'blue raspberry candy (sweet + tart), plus a clear icy exhale.' },
  { brandId: 'geekbar-pulse', name: 'Miami Mint', code: '(GB P)', description: 'clean peppermint + a bit of spearmint, smooth but very cool, like mint gum.' },
  { brandId: 'geekbar-pulse', name: 'Strawberry B-Pop', code: '(GB P)', description: 'strawberry candy/lollipop with some bubblegum sweetness and light ice.' },
  { brandId: 'geekbar-pulse', name: 'Fcuking FAB', code: '(GB P)', description: 'mixed berry candy with a “mystery” sweet note, more candy than realistic fruit.' },
  { brandId: 'geekbar-pulse', name: 'Juicy Peach', code: '(GB P)', description: 'sweet ripe peach, slightly tangy, low or no ice (depends on batch/retailer).' },
  { brandId: 'geekbar-pulse', name: 'Mexico Mango', code: '(GB P)', description: 'rich tropical mango, a bit honey-like, sometimes light cooling.' },
  { brandId: 'geekbar-pulse', name: 'Sour Apple Ice', code: '(GB P)', description: 'green apple candy with strong sour note; “Ice” adds menthol.' },
  { brandId: 'geekbar-pulse', name: 'Tropical Rainbow Blast', code: '(GB P)', description: 'mixed tropical fruits (pineapple, mango, passion fruit style) with a punch/candy vibe.' },
  { brandId: 'geekbar-pulse', name: 'California Cherry', code: '(GB P)', description: 'sweet cherry with light tartness, cherry candy more than realistic.' },
  { brandId: 'geekbar-pulse', name: 'Strawberry Mango', code: '(GB P)', description: 'juicy strawberry plus tropical mango, mid-sweet, light to medium ice.' },
  { brandId: 'geekbar-pulse', name: 'Strawberry Banana', code: '(GB P)', description: 'smoothie-style, creamy banana plus sweet strawberry, usually softer ice or none.' },
  { brandId: 'geekbar-pulse', name: 'Dragon Melon', code: '(GB P)', description: 'dragon fruit + melon (often honeydew), soft tropical, sweeter finish.' },
  { brandId: 'geekbar-pulse', name: 'Black Cherry', code: '(GB P)', description: 'darker cherry profile, deeper sweetness and mild tart finish.' },
  { brandId: 'geekbar-pulse', name: 'Berry Bliss', code: '(GB P)', description: 'mixed berries (strawberry, blueberry, raspberry) balanced sweet/tart.' },
  { brandId: 'geekbar-pulse', name: 'White Gummy Ice', code: '(GB P)', description: 'tastes like white gummy bear candy; very sweet, slightly tangy; “Ice” adds menthol.' },
  { brandId: 'geekbar-pulse', name: 'OMG Blow Pop', code: '(GB P)', description: 'lollipop + bubblegum core; fruit changes (mixed fruit, grape, sour apple), sweetness is high, some have light ice.' },
  { brandId: 'geekbar-pulse', name: 'Cherry Bomb', code: '(GB P)', description: 'strong cherry candy, starts sweet then more intense, sometimes a tiny “fizz” candy feel.' },
  { brandId: 'geekbar-pulse', name: 'Frozen Watermelon', code: '(GB P)', description: 'classic sweet watermelon but with a very cold inhale/exhale.' },
  { brandId: 'geekbar-pulse', name: 'Frozen Blackberry Fab', code: '(GB P)', description: 'sweet–tart blackberry candy with big ice layer.' },
  { brandId: 'geekbar-pulse', name: 'Frozen Pina Colada', code: '(GB P)', description: 'pineapple + coconut cocktail with strong coolness.' },
  { brandId: 'geekbar-pulse', name: 'Frozen Strawberry', code: '(GB P)', description: 'sweet ripe strawberry with heavy menthol.' },
  { brandId: 'geekbar-pulse', name: 'Frozen Cherry Apple', code: '(GB P)', description: 'tart apple + sweet cherry plus icy finish.' },
  { brandId: 'geekbar-pulse', name: 'Frozen White Grape', code: '(GB P)', description: 'light, slightly floral white grape with a crisp ice hit.' },
  { brandId: 'geekbar-pulse', name: 'Sour Strawberry', code: '(GB P)', description: 'sweet strawberry with strong sour candy coating.' },
  { brandId: 'geekbar-pulse', name: 'Sour Watermelon Drop', code: '(GB P)', description: 'juicy watermelon with tangy sour belt/powder candy vibe.' },
  { brandId: 'geekbar-pulse', name: 'Sour Blue Dust', code: '(GB P)', description: 'blue raspberry powder-candy/”dust,” very sour and sweet.' },
  { brandId: 'geekbar-pulse', name: 'Sour Cranapple', code: '(GB P)', description: 'cranberry + apple sour candy blend, tart and sharp.' },
  { brandId: 'geekbar-pulse', name: 'Sour Gush', code: '(GB P)', description: 'mixed sour fruit candy, like gusher/soft candy style.' },
  { brandId: 'geekbar-pulse', name: 'Blue Mint', code: '(GB P)', description: 'peppermint + blueberry sweetness, quite cool.' },
  { brandId: 'geekbar-pulse', name: 'BlackMintz', code: '(GB P)', description: 'different mint bases (peppermint/spearmint/stone mint) with varying strength of menthol and slight sweetness.' },
  { brandId: 'geekbar-pulse', name: 'Orange Creamsicle', code: '(GB P)', description: 'orange popsicle plus vanilla cream, light ice.' },
  { brandId: 'geekbar-pulse', name: 'Grape Lemon', code: '(GB P)', description: 'grape candy plus tart lemon, lemonade-style.' },

  // Geek Bar Pulse X
  { brandId: 'geekbar-pulsex', name: 'Banana Taffy Freeze', code: '(GB PX)', description: 'Sweet banana taffy candy with a creamy note and a strong icy finish.' },
  { brandId: 'geekbar-pulsex', name: 'Berry Cherry Lime (Platinum Edition)', code: '(GB PX)', description: 'Mixed berry and cherry candy with a squeeze of lime, sweet-tart and slightly icy.' },
  { brandId: 'geekbar-pulsex', name: 'Blackberry Blueberry', code: '(GB PX)', description: 'Dark blackberry and sweet blueberry mix with light cooling.' },
  { brandId: 'geekbar-pulsex', name: 'Blackberry B-Pop', code: '(GB PX)', description: 'Bold sweet blackberry “soda/candy” style flavor, juicy and vibrant with little or no ice.' },
  { brandId: 'geekbar-pulsex', name: 'Blue Rancher', code: '(GB PX)', description: 'Blue raspberry hard-candy profile, sweet and tangy with light or no ice.' },
  { brandId: 'geekbar-pulsex', name: 'Blue Razz Ice', code: '(GB PX)', description: 'Classic blue raspberry candy with clear sweetness and a noticeable menthol exhale.' },
  { brandId: 'geekbar-pulsex', name: 'Blueberry Jam', code: '(GB PX)', description: 'Sticky blueberry jam vibe, rich and sweet, minimal cooling.' },
  { brandId: 'geekbar-pulsex', name: 'Cherry Lemon', code: '(GB PX)', description: 'Sweet cherry plus sharp lemon, like sour cherry candy with a citrus edge.' },
  { brandId: 'geekbar-pulsex', name: 'Cola Slush', code: '(GB PX)', description: 'Fizzy cola soda slushy with caramel-cola notes and strong ice.' },
  { brandId: 'geekbar-pulsex', name: 'Cool Mint', code: '(GB PX)', description: 'Clean mint/menthol, lightly sweet for cold freshness.' },
  { brandId: 'geekbar-pulsex', name: 'Dragon Fruit Lemonade', code: '(GB PX)', description: 'Exotic dragon fruit blended into tart lemonade, tropical and refreshing.' },
  { brandId: 'geekbar-pulsex', name: 'Grape Ice Jam / Grape Ice', code: '(GB PX)', description: 'Grape candy soda style with a smooth, sweet icy finish.' },
  { brandId: 'geekbar-pulsex', name: 'Grapefruit Refresher', code: '(GB PX)', description: 'Bright grapefruit citrus mix, tart and slightly sweet, very refreshing.' },
  { brandId: 'geekbar-pulsex', name: 'Kiwi Passionfruit Guava', code: '(GB PX)', description: 'Tropical trio of tangy kiwi, fragrant passionfruit and soft guava.' },
  { brandId: 'geekbar-pulsex', name: 'Lemon Heads', code: '(GB PX)', description: 'Sharp lemon candy sweetness with a noticeable tart bite.' },
  { brandId: 'geekbar-pulsex', name: 'Lemon Tart', code: '(GB PX)', description: 'Lemon dessert with a pastry/cream vibe, sweet and bakery-style.' },
  { brandId: 'geekbar-pulsex', name: 'Lime Berry Orange', code: '(GB PX)', description: 'Lime-forward citrus with mixed berries and orange, bright and sweet-sour.' },
  { brandId: 'geekbar-pulsex', name: 'Miami Mint', code: '(GB PX)', description: 'Straight mint/menthol with very little sweetness, crisp and cold.' },
  { brandId: 'geekbar-pulsex', name: 'Orange Fcuking Fab', code: '(GB PX)', description: 'Bold orange plus mixed tropical fruits, juicy and candy-like.' },
  { brandId: 'geekbar-pulsex', name: 'Orange Slush', code: '(GB PX)', description: 'Orange soda slushy, sweet and tangy with a strong icy texture.' },
  { brandId: 'geekbar-pulsex', name: 'Peach Berry Lime Ice / Raspberry Peach Lime', code: '(GB PX)', description: 'Peach and berries with a lime kick, zesty with a medium cool finish.' },
  { brandId: 'geekbar-pulsex', name: 'Peach Perfect Slush', code: '(GB PX)', description: 'Ripe peach slushy, juicy and sweet with heavy ice.' },
  { brandId: 'geekbar-pulsex', name: 'Pineapple Ice', code: '(GB PX)', description: 'Bright pineapple juice flavor with a clear, cold menthol finish.' },
  { brandId: 'geekbar-pulsex', name: 'Sour Apple Ice', code: '(GB PX)', description: 'Green apple candy, tart and sour with a noticeable ice hit.' },
  { brandId: 'geekbar-pulsex', name: 'Sour Fcuking Fab', code: '(GB PX)', description: 'Tropical fruit base with a strong sour candy twist, intense and loud.' },
  { brandId: 'geekbar-pulsex', name: 'Sour Mango Pineapple', code: '(GB PX)', description: 'Mango and pineapple base with sour candy and a refreshing chill.' },
  { brandId: 'geekbar-pulsex', name: 'Sour Pink Dust (Platinum Edition)', code: '(GB PX)', description: 'Pink candy sherbet style with a heavy sour sugar vibe.' },
  { brandId: 'geekbar-pulsex', name: 'Sour Straws', code: '(GB PX)', description: 'Rainbow sour candy straw style, mixed fruit with strong tartness.' },
  { brandId: 'geekbar-pulsex', name: 'Strawberry B-Pop', code: '(GB PX)', description: 'Sweet strawberry candy or soda style, juicy and straightforward.' },
  { brandId: 'geekbar-pulsex', name: 'Strawberry Banana Ice', code: '(GB PX)', description: 'Smooth strawberry-banana smoothie vibe with a cool exhale.' },
  { brandId: 'geekbar-pulsex', name: 'Strawberry Colada', code: '(GB PX)', description: 'Strawberry layered into a creamy pineapple + coconut mix.' },
  { brandId: 'geekbar-pulsex', name: 'Strawberry Jam', code: '(GB PX)', description: 'Rich dessert-style strawberry jam, sweet with minimal cooling.' },
  { brandId: 'geekbar-pulsex', name: 'Strawberry Kiwi Ice', code: '(GB PX)', description: 'Sweet strawberry with tangy kiwi and a noticeable icy finish.' },
  { brandId: 'geekbar-pulsex', name: 'Strawberry Mango', code: '(GB PX)', description: 'Juicy mango with ripe strawberry, smooth tropical blend with light chill.' },
  { brandId: 'geekbar-pulsex', name: 'Strawberry Watermelon', code: '(GB PX)', description: 'Sweet watermelon juice/candy mix with a clean, cold menthol finish.' },
  { brandId: 'geekbar-pulsex', name: 'White Peach Raspberry', code: '(GB PX)', description: 'Soft white peach with tart raspberry, refined and lightly cooled.' },
  { brandId: 'geekbar-pulsex', name: 'Wild Cherry Slush', code: '(GB PX)', description: 'Bold cherry slushy flavor, sweet with a slush-style icy kick.' },

  // Tyson 30K
  { brandId: 'tyson-30k', name: 'Apple Melonberry', code: '(T30)' },
  { brandId: 'tyson-30k', name: 'Blue Razz', code: '(T30)' },
  { brandId: 'tyson-30k', name: 'Clear', code: '(T30)' },
  { brandId: 'tyson-30k', name: 'Cool Mint', code: '(T30)' },
  { brandId: 'tyson-30k', name: 'Frozen Banana', code: '(T30)' },
  { brandId: 'tyson-30k', name: 'Frozen Blueberry', code: '(T30)' },
  { brandId: 'tyson-30k', name: 'Frozen Grape', code: '(T30)' },
  { brandId: 'tyson-30k', name: 'Frozen Mango', code: '(T30)' },
  { brandId: 'tyson-30k', name: 'Frozen Peach', code: '(T30)' },
  { brandId: 'tyson-30k', name: 'Frozen Strawberry', code: '(T30)' },
  { brandId: 'tyson-30k', name: 'Green Apple', code: '(T30)' },
  { brandId: 'tyson-30k', name: 'Menthol', code: '(T30)' },
  { brandId: 'tyson-30k', name: 'Strawberry Banana', code: '(T30)' },
  { brandId: 'tyson-30k', name: 'Strawberry Watermelon', code: '(T30)' },
  { brandId: 'tyson-30k', name: 'Tobacco', code: '(T30)' },
  { brandId: 'tyson-30k', name: 'Watermelon', code: '(T30)' },

  // Olit Hookalit
  { brandId: 'olit-hookalit', name: 'Blue Razz', code: '(OH)' },
  { brandId: 'olit-hookalit', name: 'Blueberry Ice', code: '(OH)' },
  { brandId: 'olit-hookalit', name: 'Cool Mint', code: '(OH)' },
  { brandId: 'olit-hookalit', name: 'Grape Ice', code: '(OH)' },
  { brandId: 'olit-hookalit', name: 'Grape Mint', code: '(OH)' },
  { brandId: 'olit-hookalit', name: 'Lady Killer', code: '(OH)' },
  { brandId: 'olit-hookalit', name: 'Lemon Mint', code: '(OH)' },
  { brandId: 'olit-hookalit', name: 'Love 66', code: '(OH)' },
  { brandId: 'olit-hookalit', name: 'Lucid Dream', code: '(OH)' },
  { brandId: 'olit-hookalit', name: 'Magic Love', code: '(OH)' },
  { brandId: 'olit-hookalit', name: 'Miami Mint', code: '(OH)' },
  { brandId: 'olit-hookalit', name: 'Mixed Berries', code: '(OH)' },
  { brandId: 'olit-hookalit', name: 'Passion Fruit', code: '(OH)' },
  { brandId: 'olit-hookalit', name: 'Peach Ice', code: '(OH)' },
  { brandId: 'olit-hookalit', name: 'Peach Mango Watermelon', code: '(OH)' },
  { brandId: 'olit-hookalit', name: 'Pineapple Coconut', code: '(OH)' },
  { brandId: 'olit-hookalit', name: 'Strawberry Kiwi', code: '(OH)' },
  { brandId: 'olit-hookalit', name: 'Strawberry Punch', code: '(OH)' },
  { brandId: 'olit-hookalit', name: 'Two Apple Shisha', code: '(OH)' },
  { brandId: 'olit-hookalit', name: 'Watermelon Ice', code: '(OH)' },
  { brandId: 'olit-hookalit', name: 'Watermelon Strawberry Melon', code: '(OH)' },
  { brandId: 'olit-hookalit', name: 'Brown Ale', code: '(OH)' },
  { brandId: 'olit-hookalit', name: 'Cherry Mint', code: '(OH)' },

  // Mad Labs
  { brandId: 'mad-labs', name: 'Watermelon Z', code: '(ML)', description: 'Indica-dominant with fruity, calming effects.', strains: ['Indica-Dominant'] },
  { brandId: 'mad-labs', name: 'Peach Rings', code: '(ML)', description: 'Relaxing, peach-forward indica.', strains: ['Indica-Dominant'] },
  { brandId: 'mad-labs', name: 'Lemon Cherry Gelato', code: '(ML)', description: 'Balanced hybrid with dessert-like sweetness.', strains: ['Balanced / Hybrid'] },
  { brandId: 'mad-labs', name: 'Guava Kush', code: '(ML)', description: 'Hybrid with tropical fruit + mellow relaxation.', strains: ['Balanced / Hybrid'] },
  { brandId: 'mad-labs', name: 'Sherbacio', code: '(ML)', description: 'Balanced hybrid with sherbet + creamy tones.', strains: ['Balanced / Hybrid'] },
  { brandId: 'mad-labs', name: 'Blue Dream', code: '(ML)', description: 'Classic sativa-dominant hybrid with uplift + relaxed body.', strains: ['Sativa / Sativa-Dominant'] },
  { brandId: 'mad-labs', name: 'Pixie Dust', code: '(ML)', description: 'Bright sativa with energetic, euphoric lift.', strains: ['Sativa / Sativa-Dominant'] },
  { brandId: 'mad-labs', name: 'Horchata Latto', code: '(ML)', description: 'Sativa-leaning hybrid with warm spice + uplifting energy.', strains: ['Sativa / Sativa-Dominant'] },
  { brandId: 'mad-labs', name: 'Blue Razz', code: '(ML)', description: 'Lively sativa with vibrant berry profile.', strains: ['Sativa / Sativa-Dominant'] },
  { brandId: 'mad-labs', name: 'Jet Fuel', code: '(ML)', description: 'Indica-leaning hybrid with diesel character and calm vibes.', strains: ['Indica-Leaning Hybrid'] },
];

export const THC_BRANDS: Brand[] = [
  { id: 'muha-meds', name: 'Muha Meds', tagline: 'Premium THC Experience', puffRange: '2000mg', description: 'High quality THC disposables.', image: 'https://placehold.co/600x600/1a1a1a/D4AF37?text=Muha+Meds', category: 'thc-disposables' },
  { id: 'mellow-fellow', name: 'Mellow Fellow', tagline: 'Chill Vibes Only', puffRange: '2000mg', description: 'Expertly crafted blends for relaxation.', image: 'https://placehold.co/600x600/1a1a1a/D4AF37?text=Mellow+Fellow', category: 'thc-disposables' },
  { id: 'mad-labs', name: 'Mad Labs', tagline: 'Innovation in every hit', puffRange: '2000mg', description: 'Cutting edge extraction technology.', image: 'https://placehold.co/600x600/1a1a1a/D4AF37?text=Mad+Labs', category: 'thc-disposables' },
  { id: 'california-honey', name: 'California Honey', tagline: 'Golden Standard', puffRange: '1000mg', description: 'Pure and potent California honey oil.', image: 'https://placehold.co/600x600/1a1a1a/D4AF37?text=California+Honey', category: 'thc-disposables' },
  { id: 'big-chiefs', name: 'Big Chiefs', tagline: 'Stay Big', puffRange: '1000mg', description: 'Authentic and verified premium extracts.', image: 'https://placehold.co/600x600/1a1a1a/D4AF37?text=Big+Chiefs', category: 'thc-disposables' },
  { id: 'boutique-switch', name: 'Boutique Switch', tagline: 'Flip the Switch', puffRange: '2000mg', description: 'Premium boutique-style THC disposables.', image: 'https://placehold.co/600x600/1a1a1a/D4AF37?text=Boutique+Switch', category: 'thc-disposables' }
];

export const EDIBLE_BRANDS: Brand[] = [
  { id: '4ever-gummies', name: '4ever Gummies', tagline: 'Gummies That Last', puffRange: '', description: 'Premium edible gummies for a lasting experience.', image: 'https://placehold.co/600x600/2d1b69/ffffff?text=4ever+Gummies', category: 'edibles' },
  { id: 'truemoola', name: 'Truemoola', tagline: 'True Quality, True Value', puffRange: '', description: 'High quality edibles at the best value.', image: 'https://placehold.co/600x600/2d1b69/ffffff?text=Truemoola', category: 'edibles' },
  { id: 'fun-cube', name: 'Fun Cube', tagline: 'Fun in Every Bite', puffRange: '', description: 'Delicious cube-shaped edibles for every occasion.', image: 'https://placehold.co/600x600/2d1b69/ffffff?text=Fun+Cube', category: 'edibles' },
  { id: 'polka-dot-shroom-bar', name: 'Polka Dot Shroom Bar', tagline: 'A Magical Experience', puffRange: '', description: 'Premium shroom bars with a unique twist.', image: 'https://placehold.co/600x600/2d1b69/ffffff?text=Polka+Dot', category: 'edibles' }
];

export const WRAPS_BRANDS: Brand[] = [
  { id: 'sweet-wood-regular', name: 'Sweet Wood Regular', tagline: 'Natural leaf wraps', puffRange: '', description: 'Premium natural leaf wraps for a smooth experience.', image: 'https://placehold.co/600x600/1a1a1a/D4AF37?text=Sweet+Wood', category: 'wraps-and-blunts' },
  { id: 'sweet-wood-flat', name: 'Sweet Wood Flat', tagline: 'Consistent and slow burning', puffRange: '', description: 'Flat leaf wraps designed for easy rolling.', image: 'https://placehold.co/600x600/1a1a1a/D4AF37?text=Sweet+Wood+Flat', category: 'wraps-and-blunts' },
  { id: 'backwood', name: 'Backwood', tagline: 'Wild & Mild', puffRange: '', description: 'All-natural tobacco leaf wraps known for their rugged look and rich flavor.', image: 'https://placehold.co/600x600/1a1a1a/D4AF37?text=Backwood', category: 'wraps-and-blunts' },
  { id: 'truewraps', name: 'Truewraps', tagline: 'Pure tobacco satisfaction', puffRange: '', description: 'High-quality tobacco wraps for a traditional experience.', image: 'https://placehold.co/600x600/1a1a1a/D4AF37?text=Truewraps', category: 'wraps-and-blunts' },
  { id: 'blk', name: 'BLK', tagline: 'Bold and smooth', puffRange: '', description: 'Smooth tip wraps with a variety of rich flavors.', image: 'https://placehold.co/600x600/1a1a1a/D4AF37?text=BLK', category: 'wraps-and-blunts' },
  { id: 'dutch-master', name: 'Dutch Master', tagline: 'The Master of wraps', puffRange: '', description: 'Classic slow-burning wraps with a signature aroma.', image: 'https://placehold.co/600x600/1a1a1a/D4AF37?text=Dutch+Master', category: 'wraps-and-blunts' },
  { id: 'game', name: 'Game', tagline: 'Get in the game', puffRange: '', description: 'Thin, slow-burning leaves available in many popular flavors.', image: 'https://placehold.co/600x600/1a1a1a/D4AF37?text=Game', category: 'wraps-and-blunts' },
  { id: 'bluntville', name: 'BLuntville', tagline: 'Fast or slow, it’s up to you', puffRange: '', description: 'Triple-wrapped cigars that allow for a customized smoking speed.', image: 'https://placehold.co/600x600/1a1a1a/D4AF37?text=Bluntville', category: 'wraps-and-blunts' },
  { id: 'fireleaf', name: 'Fireleaf', tagline: 'Hot and fresh', puffRange: '', description: 'Unique fire-cured tobacco wraps with intense flavor.', image: 'https://placehold.co/600x600/1a1a1a/D4AF37?text=Fireleaf', category: 'wraps-and-blunts' },
  { id: 'big-dawg', name: 'Big Dawg', tagline: 'For the big dogs', puffRange: '', description: 'Large capacity wraps for an extended session.', image: 'https://placehold.co/600x600/1a1a1a/D4AF37?text=Big+Dawg', category: 'wraps-and-blunts' },
  { id: 'grabba-leaf', name: 'Grabba Leaf', tagline: 'Whole leaf authenticity', puffRange: '', description: '100% natural whole tobacco leaves for a pure, robust flavor.', image: 'https://placehold.co/600x600/1a1a1a/D4AF37?text=Grabba+Leaf', category: 'wraps-and-blunts' },
  { id: 'crush-grabba', name: 'Crush Grabba', tagline: 'Crush it your way', puffRange: '', description: 'Pre-crushed grabba leaf for easy mixing and rolling.', image: 'https://placehold.co/600x600/1a1a1a/D4AF37?text=Crush+Grabba', category: 'wraps-and-blunts' }
];

const getProfile = (name: string): string[] => {
  const profiles = [];
  if (name.toLowerCase().includes('ice') || name.toLowerCase().includes('frozen') || name.toLowerCase().includes('cool') || name.toLowerCase().includes('menthol')) profiles.push('Ice');
  if (name.toLowerCase().includes('dessert') || name.toLowerCase().includes('custard') || name.toLowerCase().includes('cream') || name.toLowerCase().includes('cake') || name.toLowerCase().includes('tart')) profiles.push('Dessert');
  if (name.toLowerCase().includes('tobacco')) profiles.push('Tobacco');
  if (profiles.length === 0) profiles.push('Fruity');
  return profiles;
};

const generateProducts = (): Product[] => {
  const allBrands = [...BRANDS, ...THC_BRANDS, ...EDIBLE_BRANDS, ...WRAPS_BRANDS];
  return RAW_PRODUCT_DATA.map((item, index) => {
    const brand = allBrands.find(b => b.id === item.brandId)!;
    const isNicFree = brand.id.includes('nonic');

    return {
      id: `prod-${index + 1}`,
      storeId: 'goldmine', // Default for static data
      brandId: brand.id,
      brandName: brand.name,
      category: brand.category || 'disposable-vapes', // Inherit from brand
      name: item.name,
      puffCount: parseInt(brand.puffRange.split(' ')[0]) || 5000,
      nicotine: isNicFree ? '0 mg (No Nicotine)' : brand.id === 'olit-hookalit' ? '0.35%' : '5%',
      isNicotineFree: isNicFree,
      flavorProfile: getProfile(item.name) as any,
      description: `Experience the premium taste of ${item.name} from ${brand.name}.`,
      // Default initial static properties
      stockQuantity: 100, // Default stock
      inStock: true,
      lowStockThreshold: 10,
      price: brand.id === 'mad-labs' ? 35.00 :
        brand.id === 'cali-ul8000' ? 19.99 :
          brand.id === 'cali-20000' ? 24.99 :
            brand.id === 'geekbar-pulse' ? 19.99 :
              brand.id === 'geekbar-pulsex' ? 24.99 :
                brand.id === 'tyson-30k' ? 25.00 :
                  brand.id === 'olit-hookalit' ? 30.00 :
                    brand.id === 'airbar-diamond' ? 10.00 :
                      brand.id === '4ever-gummies' ? 10.00 :
                        brand.id === 'fun-cube' ? 5.00 :
                          19.99, // Default price
      channel: 'both', // Default channel
      image: (item as any).image || brand.image, // Use specific product image if available, fallback to brand image

      // New defaults
      battery: brand.id === 'tyson-30k' ? '850 mAh' : brand.id === 'olit-hookalit' ? '1300 mAh' : ((item as any).battery || '650 mAh'),
      isRechargeable: (item as any).isRechargeable ?? true,
      aboutText: brand.description,
      flavorText: (item as any).description || `A rich and authentic ${item.name} flavor profile.`,
      strains: (item as any).strains || [],
      features: brand.id === 'mad-labs'
        ? [
          '2 grams of THC oil',
          'Full-spectrum extract',
          'High THC potency',
          'Strain-specific terpene flavors',
          'No PG, VG, or vitamin E acetate',
          'Ceramic coil for smooth, even heating',
          'Rechargeable battery (USB-C)',
          'Draw-activated (no buttons)',
          'Lab-tested for purity and potency'
        ]
        : brand.id === 'geekbar-pulsex'
          ? [
            'Up to 25,000 puffs (Regular Mode)',
            'Pulse Mode for a powerful hit',
            'World’s first 3D curved screen',
            'Dual mesh coil for consistent vapor',
            'Fast charging & pre-filled',
            'Sleek premium tech design'
          ]
          : brand.id === 'tyson-30k'
            ? [
              'Up to 30,000 puffs per device',
              '16 mL prefilled e-liquid capacity',
              '5% (50 mg) salt nicotine strength',
              'Triple mesh coil for stronger flavor',
              'Adjustable airflow & Dual power modes',
              '3D curved display screen'
            ]
            : brand.id === 'olit-hookalit'
              ? [
                'Up to 40,000 puffs (MTL Mode)',
                '40 mL massive e-liquid capacity',
                '0.35% nicotine (E-Hookah style)',
                '1300 mAh high-capacity battery',
                'Dual power modes (MTL/DTL)',
                '0.6 Ω LIT mesh coil for clouds'
              ]
              : ['Long-lasting Battery', 'Premium Mesh Coil', 'Smooth Airflow']
    };
  });
};

export const INITIAL_PRODUCTS = generateProducts();

export const ADMIN_ACCOUNTS = [
  { email: "goldmine@tooughyuff.com", password: "password123", storeId: "goldmine" },
  { email: "ten2ten@tooughyuff.com", password: "password123", storeId: "ten2ten" },
  { email: "admin@tooughyuff.com", password: "password123", storeId: "goldmine" } // Backwards compatibility / Super admin fallback
];
